lib_LTLIBRARIES = liburbackupclient_fsimageplugin.la
liburbackupclient_fsimageplugin_la_SOURCES = dllmain.cpp ../stringtools.cpp filesystem.cpp FSImageFactory.cpp pluginmgr.cpp vhdfile.cpp
noinst_HEADERS = filesystem.h FSImageFactory.h IFilesystem.h IFSImageFactory.h IVHDFile.h pluginmgr.h vhdfile.h fs/ntfs.h fs/unknown.h
AM_CXXFLAGS = -DLINUX