copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release Service\Server.exe" "data_service\urbackup_srv.exe"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release Server\urbackupserver.dll" "data\urbackupserver.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release Server PreVista\urbackupserver.dll" "data\urbackupserver_prevista.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\release\fsimageplugin.dll" "data\fsimageplugin.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\pychart\pychart.py" "data_common\pychart\pychart.py"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\urbackupserver\www\*" "data_common\urbackup\www\"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release\pychart.dll" "data\pychart.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release\downloadplugin.dll" "data\downloadplugin.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release\httpserver.dll" "data\httpserver.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release\urlplugin.dll" "data\urlplugin.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\urbackup\status.htm" "data_common\urbackup\status.htm"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\Release\cryptoplugin.dll" "data\cryptoplugin.dll"


copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\Release Service\Server.exe" "data_service_x64\urbackup_srv.exe"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\Release Server\urbackupserver.dll" "data_x64\urbackupserver.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\Release Server PreVista\urbackupserver.dll" "data_x64\urbackupserver_prevista.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\release\fsimageplugin.dll" "data_x64\fsimageplugin.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\release\pychart.dll" "data_x64\pychart.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\release\downloadplugin.dll" "data_x64\downloadplugin.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\release\httpserver.dll" "data_x64\httpserver.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\release\urlplugin.dll" "data_x64\urlplugin.dll"
copy /Y "D:\Developement\MSVCProjects\UrBackupBackend\x64\Release\cryptoplugin.dll" "data_x64\cryptoplugin.dll"
pause