const int DONT_SHOW_SETTINGS=1;
const int DONT_ALLOW_PAUSE=2;
const int DONT_ALLOW_STARTING_FILE_BACKUPS=4;
const int DONT_ALLOW_STARTING_IMAGE_BACKUPS=8;
const int DONT_ALLOW_CONFIG_PATHS=16;
const int DONT_SHOW_LOGS=32;