#!/bin/sh

set -e

SNAP_ID=$1
SNAP_MOUNTPOINT="$2"

if ! test -e $SNAP_MOUNTPOINT
then
        echo "Snapshot at $SNAP_MOUNTPOINT was already removed"
        exit 0
fi

if ! df -T -P | egrep "${SNAP_MOUNTPOINT}\$" > /dev/null 2>&1
then
	echo "Snapshot is not mounted. Already removed"
	rmdir "${SNAP_MOUNTPOINT}"
	exit 0
fi

VOLNAME=`lsblk -r --output "NAME,MOUNTPOINT" --paths | egrep " ${SNAP_MOUNTPOINT}\$ | head -n 1 | tr -s " " | cut -d" " -f1"`
if [ "x$VOLNAME" = x ]
then
    echo "Could not find LVM volume for mountpoint ${SNAP_MOUNTPOINT}"
    exit 1
fi

echo "Unmounting $VOLNAME at /mnt/urbackup_snaps/$SNAP_ID..."

if ! umount /mnt/urbackup_snaps/$SNAP_ID
then
        sleep 10
        umount /mnt/urbackup_snaps/$SNAP_ID
fi

rmdir "${SNAP_MOUNTPOINT}"

echo "Destroying LVM snapshot $VOLNAME..."

lvremove -f "$VOLNAME"
