#!/bin/sh

set -e

if test ! -f "/Library/Application Support/UrBackup Client/var/urbackup/macOS_exclusion_overrides.txt"
then
    cp "$2/Contents/Resources/macOS_exclusion_overrides.txt" "/Library/Application Support/UrBackup Client/var/urbackup/macOS_exclusion_overrides.txt"
    chmod 755 "/Library/Application Support/UrBackup Client/var/urbackup/macOS_exclusion_overrides.txt"
fi

if test -e "$1.cfg"
then
	cp "$1.cfg" "/Library/Application Support/UrBackup Client/var/urbackup/initial_settings.cfg"

	if test ! -e "/Library/Application Support/UrBackup Client/var/urbackup/server_idents.txt"
	then
		cp "$1.ident" "/Library/Application Support/UrBackup Client/var/urbackup/server_idents.txt"
	fi
fi

/bin/launchctl load "/Library/LaunchDaemons/org.urbackup.client.plist"
/bin/launchctl start "org.urbackup.client.backend"


/bin/launchctl load "/Library/LaunchAgents/org.urbackup.client.plist"
/bin/launchctl start "org.urbackup.client.frontend"
