#ifndef DATABASE_H
#define DATABASE_H

const DATABASE_ID URBACKUPDB_SERVER=20;
const DATABASE_ID URBACKUPDB_SERVER_FILES = 23;
const DATABASE_ID URBACKUPDB_SERVER_LINKS = 24;
const DATABASE_ID URBACKUPDB_SERVER_LINK_JOURNAL = 25;
const DATABASE_ID URBACKUPDB_SERVER_SETTINGS=30;

#endif //DATABASE_H