lib_LTLIBRARIES = liburbackupserver_cryptoplugin.la
liburbackupserver_cryptoplugin_la_SOURCES = dllmain.cpp AESDecryption.cpp CryptoFactory.cpp pluginmgr.cpp AESEncryption.cpp ZlibCompression.cpp ZlibDecompression.cpp
liburbackupserver_cryptoplugin_la_LIBADD = $(CRYPTO_PP_LIBS)
noinst_HEADERS = AESEncryption.h AESDecryption.h IAESDecryption.h ICryptoFactory.h pluginmgr.h IAESEncryption.h CryptoFactory.h IZlibCompression.h IZlibDecompression.h ZlibCompression.h ZlibDecompression.h cryptopp_inc.h
AM_CXXFLAGS = -DLINUX $(CRYPTO_PP_CPPFLAGS)
AM_LDFLAGS = $(CRYPTO_PP_LDFLAGS)
ACLOCAL_AMFLAGS = -I m4