lib_LTLIBRARIES = liburbackupclient_cryptoplugin.la
liburbackupclient_cryptoplugin_la_SOURCES = dllmain.cpp AESDecryption.cpp CryptoFactory.cpp pluginmgr.cpp AESEncryption.cpp ZlibCompression.cpp ZlibDecompression.cpp
liburbackupclient_cryptoplugin_la_LIBADD = $(CRYPTOPP_LIBS)
noinst_HEADERS = AESEncryption.h AESDecryption.h IAESDecryption.h ICryptoFactory.h pluginmgr.h IAESEncryption.h CryptoFactory.h IZlibCompression.h IZlibDecompression.h ZlibCompression.h ZlibDecompression.h cryptopp_inc.h
if WITH_FORTIFY
	AM_CPPFLAGS = -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2
endif
AM_CXXFLAGS = -DLINUX $(CRYPTOPP_CPPFLAGS)
AM_LDFLAGS = $(CRYPTOPP_LDFLAGS)
ACLOCAL_AMFLAGS = -I m4