.\" In .TH, FOO should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.\"
.\" This template provided by Tom Christiansen <tchrist@jhereg.perl.com>.
.\" 
.TH URBACKUP_SRV 1 
.SH NAME
urbackup_srv \- Process running the UrBackup Server
.SH SYNOPSIS
Do not run directly but use the wrapper script start_urbackup_server.
.PP
.SH DESCRIPTION
.\" Putting a newline after each sentence can generate better output.
This is the server process which loads all the plugins.

.SH HISTORY
Was originally intended to serve dynamic web content. This part is used for
the web interface of UrBackup now.
.SH "SEE ALSO"
.\" Always quote multiple words for .SH
.BR start_urbackup_server (1)
