.\" In .TH, FOO should be all caps, SECTION should be 1-8, maybe w/ subsection
.\" other parms are allowed: see man(7), man(1)
.\"
.\" This template provided by Tom Christiansen <tchrist@jhereg.perl.com>.
.\" 
.TH URBACKUP_CLIENT 1 
.SH NAME
urbackup_client \- Process running the UrBackup client backend
.SH SYNOPSIS
Do not run directly but use the wrapper script start_urbackup_client.
.PP
.SH DESCRIPTION
.\" Putting a newline after each sentence can generate better output.
This is the server process which loads all the plugins.

.SH "SEE ALSO"
.\" Always quote multiple words for .SH
.BR start_urbackup_client (1)
