#!/bin/sh
#
# Copyright (c) 2014-2016 Martin Raiber
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

if [ $3 != 0 ]
then
	. SYSCONFDIR/mariadbxtrabackup.conf

	TIMESTAMP=`date "+%F-%H%M%S"`
	
	[ ! -e "$MARIADB_TEMP_INCRDIR/last.new" ] || rm -R "$MARIADB_TEMP_INCRDIR/last.new"
	mkdir -p "$MARIADB_TEMP_INCRDIR/last.new"

	TIME=`date`
	echo "Starting incremental binary backup of MariaDB at $TIME..."
	xtrabackup --backup --extra-lsndir="$MARIADB_TEMP_INCRDIR/last.new" --incremental-basedir="$MARIADB_TEMP_INCRDIR/last" --target-dir="$MARIADB_TEMP_INCRDIR/incr_$TIMESTAMP"  --user="$MARIADB_USERNAME" --password="$MARIADB_PASSWORD"
	TIME=`date`
	echo "Backup of MariaDB finished at $TIME."
fi