#!/bin/sh
#
# Copyright (c) 2014-2016 Martin Raiber
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
# IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
# CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
# TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

set -e

. SYSCONFDIR/postgresbase.conf

if [ "x$POSTGRESQL_BASE_ENABLED" = x0 ]
then
	echo "POSTGRESQL_BASE_ENABLED not enabled in SYSCONFDIR/postgresbase.conf. Please enable."
	exit 1
fi

echo "Temporary folder for WAL files: $POSTGRESQL_WAL_DIR (configure in SYSCONFDIR/postgresbase.conf)"

CDIR=`dirname "$0"`
echo "Installing pre/postfilebackup scripts..."

if [ -e SYSCONFDIR/prefilebackup ]
then
	echo "ERROR: SYSCONFDIR/prefilebackup already present."
	exit 1
fi

if [ -e SYSCONFDIR/postfilebackup ]
then
	echo "ERROR: SYSCONFDIR/postfilebackup already present."
	exit 1
fi

cp "$CDIR/postgresqlprebackup" SYSCONFDIR/prefilebackup
cp "$CDIR/postgresqlpostbackup" SYSCONFDIR/postfilebackup

echo "Configuring virtual client 'wal'..."

urbackupclientctl set-settings -v virtual_clients -k wal

echo "Adding path to backup..."

mkdir -p $POSTGRESQL_WAL_DIR/{incoming,staging,backup}
chown postgres:postgres $POSTGRESQL_WAL_DIR/{incoming,staging,backup}

urbackupclientctl add-backupdir --keep -d $POSTGRESQL_WAL_DIR/backup -v wal

echo "Configured PostgreSQL backup successfully."
